version: "3.1"
services:
    mariadb:
      image: mariadb:10.1
      container_name: pdfproject-mariadb
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=50dc2592
        - MYSQL_DATABASE=pdf
        - MYSQL_USER=pdf
        - MYSQL_PASSWORD=50dc2592
      ports:
        - "8126:3306"

    webserver:
      image: httpd:2.4.29
      container_name: pdfproject-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/apache/pdfproj.conf:/usr/local/apache2/conf/pdfproj.conf
      ports:
       - "8123:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: pdfproject-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.2/fpm/conf.d/99-overrides.ini

